CREATE DATABASE `book_shop`;
CREATE TABLE `clients` (`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`client_name` VARCHAR(255) NOT NULL,
`client_surname` VARCHAR(255) NOT NULL
);
CREATE TABLE `clients_discount` (`client_id` INT UNSIGNED NOT NULL PRIMARY KEY,
`discount` DECIMAL(3,2) NOT NULL
);
CREATE TABLE `books` (`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
`book_name` VARCHAR(255) NOT NULL
);
CREATE TABLE `stock` (`book_id` INT UNSIGNED NOT NULL PRIMARY KEY,
`stock_qty` SMALLINT UNSIGNED NOT NULL
);
CREATE TABLE `sells` (`book_id` INT UNSIGNED NOT NULL PRIMARY KEY,
`sells_qty` SMALLINT UNSIGNED NOT NULL
);
CREATE TABLE `book_discount` (`book_id` INT UNSIGNED NOT NULL PRIMARY KEY,
`discount` DECIMAL(3,2) NOT NULL
);